# 1. Información del Proyecto
#sonar.projectKey=Frontende
#sonar.projectName=Frontende
#sonar.host.url=http://localhost:9000
sonar.projectKey=jorgelopez04_FrontendValidacion
sonar.projectName=FrontendValidacion
sonar.host.url=https://sonarcloud.io
sonar.organization=jorgelopez04

# CAMBIO AQUÍ: Usamos sonar.login para asegurar compatibilidad con el scanner 3.1
#sonar.login=sqp_d1ce3da8bd528d5b4ae1808e7c80aba2885e5d02
sonar.token=390a535aeb9057862a8ae0cbdcb162f5e539e2d2

# 2. Configuración de Git
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8

# 3. Rutas de Código y Tests
sonar.sources=src/app
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.projectBaseDir=.

# 4. Rutas de Cobertura (Angular)
sonar.javascript.lcov.reportPaths=coverage/frontend-tailorflow/lcov.info
sonar.typescript.lcov.reportPaths=coverage/frontend-tailorflow/lcov.info

# 5. Exclusiones
sonar.exclusions=src/app/guards/**, \
    src/app/interceptors/**, \
    src/app/services/**, \
    src/app/core/models/**, \
    src/app/app.config.ts, \
    src/app/app.routes.ts, \
    src/main.ts, \
    src/test.ts, \
    **/*.module.ts, \
    **/*.model.ts, \
    **/*.interface.ts, \
    **/*.html, \
    **/*.scss, \
    src/environments/**