# Identificación del Proyecto
sonar.organization=jorgelopez04
sonar.projectKey=jorgelopez04_FrontendValidacion
sonar.projectName=FrontendValidacion
# Mijo, recuerda que es mejor pasar el token por Jenkins, pero si lo dejas acá, que sea el actual
sonar.token=38943d8c1633edc1826eca05891a47bdd5359d98

# --- CONFIGURACIÓN DE COBERTURA ---
# Esta es la ruta que confirmamos en tu explorador de archivos para el frontend
sonar.javascript.lcov.reportPaths=coverage/frontend-tailorflow/lcov.info

# --- ANÁLISIS DE CÓDIGO ---
sonar.projectBaseDir=.
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8

# --- EXCLUSIONES (RNF1: Usabilidad e Integridad) ---
# Excluimos archivos que no necesitan pruebas unitarias o son de configuración
sonar.exclusions=**/*.spec.ts, \
                 src/environments/**, \
                 src/main.ts, \
                 src/test.ts, \
                 src/polyfills.ts, \
                 **/*.module.ts, \
                 **/*.model.ts, \
                 **/*.interface.ts, \
                 **/*.html, \
                 **/*.scss, \
                 src/app/guards/**, \
                 src/app/interceptors/**, \
                 src/app/core/models/**