sonar.host.url=https://sonarcloud.io
sonar.organization=ferrerdecaldas
sonar.projectKey=frontvalidacion
sonar.projectName=frontvalidacion
sonar.token=6a3ca86e63aa174115cf776c477403d10a29faf8

sonar.javascript.lcov.reportPaths=coverage/frontend-tailorflow/lcov.info
sonar.typescript.lcov.reportPaths=coverage/frontend-tailorflow/lcov.info

sonar.projectBaseDir=.
# Solo analizamos pages y services para llegar a las 1000 líneas rápido
sonar.sources=src/app
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/frontend-tailorflow/lcov.info

sonar.exclusions=src/app/guards/**, \
                 src/app/interceptors/**, \
                 src/app/services/**, \
                 src/app/core/models/**, \
                 src/app/app.config.ts, \
                 src/app/app.routes.ts, \
                 src/main.ts, \
                 src/test.ts, \
                 **/*.module.ts, \
                 **/*.model.ts, \
                 **/*.interface.ts, \
                 **/*.html, \
                 **/*.scss, \
                 src/environments/**